### ISSUE TITLE
Set up unit tests

### ISSUE THREAD

**Issue by renatonascalves** [wp-graphql/wp-graphql-buddypress#1]
Set up unit tests with Travis.

**Comment by renatonascalves** [comment]
@jasonbahl Can you activate Travis for this repo?

**Comment by jasonbahl** [comment]
@renatonascalves just activated. Let me know if you need anything else to get it going.

**Comment by jasonbahl** [comment]
fwiw: https://travis-ci.org/wp-graphql/wp-graphql-buddypress
