### ISSUE TITLE
Is this repo active?

### ISSUE THREAD

**Issue by peterrobertz** [wp-graphql/wp-graphql-buddypress#35]
Hey,

thank you, for your code! :-)

I would love to use activities/messages with graphql.

--

Does your members-fetch with cursors work? I dont get it, after fetchMore edges is always empty

**Comment by renatonascalves** [comment]
@peterrobertz Could you share how you are trying to use the cursor?

I'm able to fetch with the cursor properly..

**Comment by renatonascalves** [comment]
![Uploading Screen Shot 2021-03-05 at 20.23.37.png…]()

**Comment by renatonascalves** [comment]
I'm closing this ticket as invalid. Feel free to reopen it. :)
