### ISSUE TITLE
BP_XProfile_Group::get_group_ids() call to undefined function

### ISSUE THREAD

**Issue by blackge** [wp-graphql/wp-graphql-buddypress#79]
I'm running Buddyboss platform, so this might be an issue with the fork they are running. In the XProfileGroupObjectLoader.php on line 35 the call to BP_XProfile_Group::get_group_ids() is calling a function that doesn't exist. I think it should be calling BP_XProfile_Group::get()

Here's the error:
"errors": [
    {
      "debugMessage": "Call to undefined method BP_XProfile_Group::get_group_ids()",
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "user",
        "xprofileGroups"
      ],

**Comment by renatonascalves** [comment]
@blackge I'd confirm if the BuddyBoss fork has this method. The BuddyPress version does: https://github.com/buddypress/BuddyPress/blob/ecdb14d618d01cc25e333c132635d8ca304eca18/src/bp-xprofile/classes/class-bp-xprofile-group.php#L471

**Comment by nickchomey** [comment]
@blackge Did you ever have much success integrating this with BuddyBoss?

**Comment by blackge** [comment]
> @blackge Did you ever have much success integrating this with BuddyBoss?

@nickchomey We didn't. Mainly because we went down a completely different route off Wordpress.
