### ISSUE TITLE
This likely means you have cloned WPGraphQL BuddyPress from Github and need to run the command `composer install`

### ISSUE THREAD

**Issue by Xyzbarna** [wp-graphql/wp-graphql-buddypress#91]
I read that this issue was closed, but I'm having this error message in the WordPress Dashboard:

WPGraphQL BuddyPress appears to have been installed without its dependencies. It will not work properly until dependencies are installed. This likely means you have cloned WPGraphQL BuddyPress from Github and need to run the command `composer install`.

Local installation with Local (Flywheel)
Buddypress 10.0.0
WPGraphQL 1.6.12
WPGraphQL BuddyPress 0.0.1-alpha

PHP 8.0.0
WordPress 5.8.3

Thank you!

**Comment by renatonascalves** [comment]
That's correct! This version here is for development purposes only. So after cloning the plugin, you need to `composer install` to add the dependencies.
