### ISSUE TITLE
Not an Issue

### ISSUE THREAD

**Issue by brown7477** [wp-graphql/wp-graphql-buddypress#95]
I am looking to create a headless social network and was curious what it means to 'run "composer install"'
I am currently using BP and a ton of other plugins to make this work, and will be converting html templates to use as a headless front end.
Forgive me as I am new to this 'Headless' system but very excited to do this.
my email is extremeappz373@gmail.com

Thanks
Matthew Brown

**Comment by renatonascalves** [comment]
It means to use this plugin, you need to have the files loaded and composer installs those files.

I'm resolving this issue since the question is unrelated to the plugin. AFTER you start to use it and see issues, feel free to report any in this repo.

Good luck! :)
