### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages

### ISSUE THREAD

**Issue by qrahaman** [wp-graphql/wp-graphql-buddypress#98]
This is my first time executing via ssh, but this is what came back after attempted `composer install`

  Problem 1
    - Installation request for phar-io/manifest 1.0.3 -> satisfiable by phar-io/manifest[1.0.3].
    - phar-io/manifest 1.0.3 requires php ^5.6 || ^7.0 -> your PHP version (8.1.3) does not satisfy that requirement.
  Problem 2
    - Installation request for phar-io/version 2.0.1 -> satisfiable by phar-io/version[2.0.1].
    - phar-io/version 2.0.1 requires php ^5.6 || ^7.0 -> your PHP version (8.1.3) does not satisfy that requirement.
  Problem 3
    - Installation request for phpunit/php-code-coverage 6.1.4 -> satisfiable by phpunit/php-code-coverage[6.1.4].
    - phpunit/php-code-coverage 6.1.4 requires php ^7.1 -> your PHP version (8.1.3) does not satisfy that requirement.
  Problem 4
    - Installation request for phpunit/phpunit 7.5.20 -> satisfiable by phpunit/phpunit[7.5.20].
    - phpunit/phpunit 7.5.20 requires php ^7.1 -> your PHP version (8.1.3) does not satisfy that requirement.
  Problem 5
    - Installation request for sebastian/global-state 2.0.0 -> satisfiable by sebastian/global-state[2.0.0].
    - sebastian/global-state 2.0.0 requires php ^7.0 -> your PHP version (8.1.3) does not satisfy that requirement.
  Problem 6
    - phpunit/phpunit 7.5.20 requires php ^7.1 -> your PHP version (8.1.3) does not satisfy that requirement.
    - yoast/phpunit-polyfills 1.0.3 requires phpunit/phpunit ^4.8.36 || ^5.7.21 || ^6.0 || ^7.0 || ^8.0 || ^9.0 -> satisfiable by phpunit/phpunit[7.5.20].
    - Installation request for yoast/phpunit-polyfills 1.0.3 -> satisfiable by yoast/phpunit-polyfills[1.0.3].

**Comment by renatonascalves** [comment]
We do not support PHP 8 yet.

**Comment by renatonascalves** [comment]
Actually, I think phpunit 7.5 changed recently and I need to upgrade it. Our CI was passing our unit tests for PHP 8.

Let me take a look at this.

**Comment by renatonascalves** [comment]
After a bit of investigation, the issue we are dealing here is larger. So that I can properly support PHP 8+, the BuddyPress plugin will need to stop to hardcode the phpunit version. Since our unit tests use `BP_UnitTestCase` and `BP_UnitTest_Factory` extensively, we are sort of _locked_.

I have a patch incoming to BuddyPress code.

**Comment by renatonascalves** [comment]
By the way, you can install the plugin using PHP 8 by removing the `composer.lock` file locally. And running `composer install`.

**Comment by renatonascalves** [comment]
This was resolved. :)

**Comment by qrahaman** [comment]
Awesome!  Thank you.
